name: khoates
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Core Firebase package (3.x)
  firebase_core: ^3.13.0

  # Data Connect (yêu cầu firebase_core ^3.13.0 và firebase_auth 5.5.x)
  firebase_data_connect: ^0.1.4

  # Authentication (nâng lên 5.5.x để khớp với firebase_data_connect)
  firebase_auth: ^5.5.3
  url_launcher: ^6.1.7
  # Firestore (5.x tương thích với firebase_core 3.x)
  cloud_firestore: ^5.6.7

  get: ^4.6.6
  pinput: ^5.0.1
  device_info_plus: ^11.4.0
  image_picker: ^1.0.7
  permission_handler: ^12.0.0+1

  # Storage (phiên bản 12.x tương thích với firebase_core 3.x)
  firebase_storage: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
