// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsiyTaZszHLE6OapLKquKM-Bq8N5TyvXY',
    appId: '1:365491180333:web:f25dc54ba60744fc4ff9a4',
    messagingSenderId: '365491180333',
    projectId: 'khoatest123',
    authDomain: 'khoatest123.firebaseapp.com',
    storageBucket: 'khoatest123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_aSbwoPhRVTqPGF7E4Xc7S18RQ3Dotow',
    appId: '1:365491180333:android:34225fe4507a85124ff9a4',
    messagingSenderId: '365491180333',
    projectId: 'khoatest123',
    storageBucket: 'khoatest123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCESUWWoN40q5c63fquMce3NiJ5lAT2Qqg',
    appId: '1:365491180333:ios:9474131226861c674ff9a4',
    messagingSenderId: '365491180333',
    projectId: 'khoatest123',
    storageBucket: 'khoatest123.firebasestorage.app',
    iosBundleId: 'com.example.khoates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCESUWWoN40q5c63fquMce3NiJ5lAT2Qqg',
    appId: '1:365491180333:ios:9474131226861c674ff9a4',
    messagingSenderId: '365491180333',
    projectId: 'khoatest123',
    storageBucket: 'khoatest123.firebasestorage.app',
    iosBundleId: 'com.example.khoates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsiyTaZszHLE6OapLKquKM-Bq8N5TyvXY',
    appId: '1:365491180333:web:a54400f330de8aab4ff9a4',
    messagingSenderId: '365491180333',
    projectId: 'khoatest123',
    authDomain: 'khoatest123.firebaseapp.com',
    storageBucket: 'khoatest123.firebasestorage.app',
  );

}